In [3]:
%config Completer.use_jedi = False

In [1]:
import numpy as np

In [177]:
# polynomial function /regression problem
# f([x1, x2, ..., xn]) = w0 + w1.x1 + w2.x2 + .... wn.xn = y

# f(x1) = w0 + w1.x1 = y1
# f(x2) = w0 + w2.x2 = y2
# ...
# f(xn) = w0 + wn.xn = yn

w0 = 3
x = np.array([1, 2, 3, 4])
w = np.array([1, 1/2, 1/3, 1/4])

np.dot(x,w)+w0

7.0

In [193]:
# Inner Product
a = np.array([2,3,4])
b = np.array([5,6,7])

np.inner(a, b)

56

In [191]:
# dot Product
a = np.array([2,3,4])
b = np.array([5,6,7])
np.dot(a, b)

56

In [185]:
# Cross Product
a = np.array([2,3,4])
b = np.array([5,6,7])
np.cross(a, b)

array([-3,  6, -3])

In [188]:
A = np.array([[1, 2, 1],
             [4, 4, 5],
             [6, 7, 7]])

B = np.linalg.inv(A)

print(A)
print(B)

print(A*B)

print(A.dot(B))
print(np.dot(A, B))

I = np.around(A @ B, 2)
print(I)

[[1 2 1]
 [4 4 5]
 [6 7 7]]
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
[[ -7. -14.   6.]
 [  8.   4.  -5.]
 [ 24.  35. -28.]]
[[ 1.00000000e+00 -1.77635684e-15  8.88178420e-16]
 [-2.22044605e-15  1.00000000e+00  4.44089210e-15]
 [ 7.54951657e-15 -1.77635684e-15  1.00000000e+00]]
[[ 1.00000000e+00 -1.77635684e-15  8.88178420e-16]
 [-2.22044605e-15  1.00000000e+00  4.44089210e-15]
 [ 7.54951657e-15 -1.77635684e-15  1.00000000e+00]]
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0. -0.  1.]]


### Normal Eauation Model
$$
w = (X^{T}X)^{-1} X^{T} y
$$

In [172]:
# f([x1, x2, ..., xn]) = w0 + w1.x1 + w2.x2 + .... wn.xn = y

# y = f(x) = w0 + wx
# y = f(x, y) = w0 + w1.x + w2y
# y = f(x, y, z) = w0 + w1.x + w2.y + w2.z

# Define the input features and output values
X = np.array([[1400, 50, 1], [1600, 20, 0], [1700, 60, 1], [1875, 35, 0], [1100, 70, 0], [1550, 80, 1]])
y = np.array([[245000], [312000], [279000], [308000], [199000], [219000]])

# Add a column of w0 to represent the bias term
X_b = np.c_[np.random.rand(X.shape[0]), X]

# Compute the optimal parameters using the normal equation
w = np.around(np.linalg.inv(np.dot(X_b.transpose(), X_b)).dot(X_b.T).dot(y), 2)

# Print the optimal parameters
print('w0=',w[0][0], ', w1=',w[1][0], ', w2=',w[2][0], ', w3=',w[3][0])

# y = f(surface, distance, balcon) = w0 + w1.surfcace + w2.distance + w3.balcon

w0= 205515.49 , w1= 70.4 , w2= 510.62 , w3= 45289.22


In [173]:
Y = lambda surface, distance, balcon: w[0] + w[1]*surface + w[2]*distance + w[3]*balcon

Y(1400, 50, 1)

array([374895.71])

### L-Norm
$$
\left(\begin{array}{cc} 
x_{1}\\
x_{2}\\
.\\
.\\
.\\
x_{n}\\
\end{array}\right)
, |X|_{p} = (\Sigma_{i} |X_{i}|^p)^1/p
$$

In [83]:
# Define two vectors
O1 = np.array([1400, 50, 1, 5, 9, 8])
O2 = np.array([1400, 50, 1, 7, 5, 8])
O3 = np.array([1400, 50, 1, 5, 9, 6])

# Compute the L1-norm (Manhattan distance) between the two vectors
L1_norm = np.sum(np.abs(O1 - O2))
print("L1-norm similarity:", L1_norm)

L1_norm = np.sum(np.abs(O1 - O3))
print("L1-norm similarity:", L1_norm)

L1-norm similarity: 6
L1-norm similarity: 2


In [108]:
# Compute the L2-norm (Euclidean distance) between the two vectors
L2_norm = np.sqrt(np.sum((O1 - O3)**2))
print("L2-norm similarity:", L2_norm)
Threshold = 2

if L2_norm <= Threshold:
    print('Vector A and B are similar')
else:
    print('Vector A and B not are similar')

L2-norm similarity: 2.0
Vector A and B are similar


In [87]:
# Compute the Linf-norm (Chebyshev distance) between the two vectors
Linf_norm = np.max(np.abs(O1 - O3))
print("Linf-norm similarity:", Linf_norm)
# Output: Linf-norm similarity: 1

Linf-norm similarity: 2


#### The higher the L1 the lower the similarity

### Cosine Similarity 
$$
\cos (\theta ) =   \dfrac {A \cdot B} {\left\| A\right\| _{2}\left\| B\right\| _{2}} 
$$

In [ ]:
from numpy.linalg import norm
A = np.array([10, 20, 1, 50, 0, 80])
B = np.array([1200, 60, 3, 7, 4, 3])
Threshold = 0.5

cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", round(cosine, 2))

if cosine >= Threshold:
    print('Vector A and B are similar')
else:
    print('Vector A and B not are similar')

In [140]:
# Label Based Model
labels = {0:'dog', 1:'cat', 2:'cat'}

Objects = np.array([[2,1,2],# dog
                    [3,2,9], # cat
                    [-1,2,-3]# cat
                   ])

NewObj = np.array([3,4,2])# is this a dog or a cat
NewObj = np.array([1,1,1])

cosines = np.around(np.dot(Objects, NewObj)/(norm(Objects, axis=1)*norm(NewObj)), 2)
print("Cosines Similarity scores:", cosines)

np.argmax(cosines), labels[np.argmax(cosines)]

Cosines Similarity scores: [ 0.96  0.83 -0.31]


(0, 'dog')

In [176]:
# Threshold Based model
Objects = np.array([[2,1,2],# dog
                    [3,2,9], # cat
                    [-1,2,-3]# cat
                   ])

NewObj = np.array([3,4,2])# is this a dog or a cat
NewObj = np.array([1,1,1])

cosines = np.around(np.dot(Objects, NewObj)/(norm(Objects, axis=1)*norm(NewObj)), 2)
print("Cosines Similarity scores:", cosines)

Threshold = 0.8

if np.max(cosines) >= Threshold:
    print('dog')
else:
    print('cat')

Cosines Similarity scores: [ 0.96  0.83 -0.31]
dog


#### The higher the Cosine Score the higher the similarity